# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
# e.x. name: drupal
name: drupal

# The configuration of app when it is exposed to the web.
web:
    # The public directory of the app, relative to its root.
    document_root: "/docroot"
    # The front-controller script to send non-static requests to.
    passthru: "/index.php"
